apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-USERNAME
spec:
  destination:
    namespace: USERNAME-ns
    server: https://kubernetes.default.svc
  project: default
  source:
    path: user-common
    repoURL: file:///.
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
    automated:
      prune: true
      selfHeal: true
