apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- route.yaml
- svc.yaml
- ns.yaml
- network-policy.yaml
replacements:
- source:
    kind: ConfigMap
    version: v1
    name: user-config
    fieldPath: data.user-ns
  targets:
  - select:
      group: project.openshift.io
      kind: Project
      version: v1
    fieldPaths:
    - metadata.name
- source:
    kind: ConfigMap
    version: v1
    name: user-config
    fieldPath: data.user-network-policy
  targets:
  - select:
      group: networking.k8s.io
      kind: NetworkPolicy
      name: user-access-dev-env
      version: v1
    fieldPaths:
    - /metadata/name
